---
- name: Add facts
  hosts: all

  tasks:
  - name: Prepare directory
    file:
      dest: /etc/ansible/facts.d
      state: directory

  - name: Upload simple fact
    copy:
      content: "1"
      dest: /etc/ansible/facts.d/one.fact
      mode: 0444
